import type { RPPData, RubricItem } from '../../types/rpp';
import { EditorSection, Field, LineListEditor, TextArea, TextInput } from './EditorPrimitives';

function RubricEditor({ label, items, onChange }: { label: string; items: RubricItem[]; onChange: (items: RubricItem[]) => void }) {
  const update = (index: number, patch: Partial<RubricItem>) => { const next = [...items]; next[index] = { ...next[index], ...patch }; onChange(next); };
  return <div><p className="mb-2 text-[11px] font-extrabold uppercase tracking-wide text-slate-500">{label}</p><div className="space-y-3">{items.map((item, index) => <div key={index} className="rounded-lg border border-slate-200 p-3">
    <div className="grid gap-3 sm:grid-cols-2"><Field label="Aspek"><TextInput value={item.aspect} onChange={(e) => update(index, { aspect: e.target.value })} /></Field><Field label="Indikator"><TextInput value={item.indicator} onChange={(e) => update(index, { indicator: e.target.value })} /></Field></div>
    <div className="mt-3 grid gap-2 sm:grid-cols-4">{(['score1', 'score2', 'score3', 'score4'] as const).map((score, scoreIndex) => <Field key={score} label={`Skor ${scoreIndex + 1}`}><TextArea rows={3} value={item.levels[score]} onChange={(e) => update(index, { levels: { ...item.levels, [score]: e.target.value } })} /></Field>)}</div>
  </div>)}</div></div>;
}

export default function ModuleContentEditor({ rpp, onChange }: { rpp: RPPData; onChange: (rpp: RPPData) => void }) {
  if (rpp.documentFormat === 'Ringkas') return null;
  return <>
    <EditorSection title="DPL, Model & Lingkungan" description="Sunting dimensi profil, model, metode, kemitraan, dan lingkungan belajar.">
      <div className="space-y-3">{rpp.selectedDimensions.map((dimension, index) => <div key={index} className="rounded-lg border border-slate-200 p-3"><div className="grid gap-3 sm:grid-cols-2">
        {(['name', 'reason', 'indicator', 'activity', 'evidence'] as const).map((key) => <Field key={key} label={key === 'name' ? 'Dimensi' : key === 'reason' ? 'Alasan' : key === 'indicator' ? 'Indikator' : key === 'activity' ? 'Aktivitas' : 'Bukti'}>{key === 'name' ? <TextInput value={dimension[key]} onChange={(e) => { const next = [...rpp.selectedDimensions]; next[index] = { ...dimension, [key]: e.target.value }; onChange({ ...rpp, selectedDimensions: next }); }} /> : <TextArea rows={2} value={dimension[key]} onChange={(e) => { const next = [...rpp.selectedDimensions]; next[index] = { ...dimension, [key]: e.target.value }; onChange({ ...rpp, selectedDimensions: next }); }} />}</Field>)}
      </div></div>)}</div>
      <div className="mt-4 grid gap-3 sm:grid-cols-2"><Field label="Model Pembelajaran"><TextInput value={rpp.learningSettings.resolvedModel || rpp.learningSettings.model} onChange={(e) => onChange({ ...rpp, learningSettings: { ...rpp.learningSettings, model: e.target.value, resolvedModel: e.target.value } })} /></Field><Field label="Metode — pisahkan dengan koma"><TextInput value={rpp.learningSettings.methods.join(', ')} onChange={(e) => onChange({ ...rpp, learningSettings: { ...rpp.learningSettings, methods: e.target.value.split(',').map((v) => v.trim()).filter(Boolean) } })} /></Field></div>
      <div className="mt-3"><Field label="Alasan Pemilihan Model"><TextArea rows={2} value={rpp.learningSettings.modelRecommendationReason || ''} onChange={(e) => onChange({ ...rpp, learningSettings: { ...rpp.learningSettings, modelRecommendationReason: e.target.value } })} /></Field></div>
      <div className="mt-3"><Field label="Mitra Pembelajaran"><TextInput value={rpp.partnership} onChange={(e) => onChange({ ...rpp, partnership: e.target.value })} /></Field></div>
      <div className="mt-3 grid gap-3 sm:grid-cols-3">{(['physicalSpace', 'virtualSpace', 'learningCulture'] as const).map((key) => <Field key={key} label={key === 'physicalSpace' ? 'Ruang Fisik' : key === 'virtualSpace' ? 'Ruang Virtual' : 'Budaya Belajar'}><TextArea rows={2} value={rpp.environment[key]} onChange={(e) => onChange({ ...rpp, environment: { ...rpp.environment, [key]: e.target.value } })} /></Field>)}</div>
      <div className="mt-3 grid gap-3 sm:grid-cols-2"><LineListEditor label="Sarana / Alat — satu per baris" values={rpp.facilities.tools} onChange={(tools) => onChange({ ...rpp, facilities: { ...rpp.facilities, tools } })} /><LineListEditor label="Prasarana — satu per baris" values={rpp.facilities.infrastructure} onChange={(infrastructure) => onChange({ ...rpp, facilities: { ...rpp.facilities, infrastructure } })} /></div>
      <div className="mt-3"><p className="mb-2 text-[11px] font-bold text-slate-700">Pemanfaatan Digital</p><div className="space-y-2">{rpp.digitalUse.map((item, index) => <div key={index} className="grid gap-2 sm:grid-cols-2"><TextInput value={item.tool} placeholder="Perangkat / aplikasi" onChange={(e) => { const digitalUse = [...rpp.digitalUse]; digitalUse[index] = { ...item, tool: e.target.value }; onChange({ ...rpp, digitalUse }); }} /><TextInput value={item.purpose} placeholder="Tujuan penggunaan" onChange={(e) => { const digitalUse = [...rpp.digitalUse]; digitalUse[index] = { ...item, purpose: e.target.value }; onChange({ ...rpp, digitalUse }); }} /></div>)}</div></div>
    </EditorSection>

    <EditorSection title="Materi, Refleksi & Tindak Lanjut" description="Review pertanyaan pemantik, materi esensial, refleksi, remedial, dan pengayaan.">
      <LineListEditor label="Pertanyaan Pemantik — satu per baris" values={rpp.triggerQuestions} onChange={(triggerQuestions) => onChange({ ...rpp, triggerQuestions })} />
      <div className="mt-3"><Field label="Konsep Inti"><TextArea rows={2} value={rpp.essentialMaterial.coreConcept} onChange={(e) => onChange({ ...rpp, essentialMaterial: { ...rpp.essentialMaterial, coreConcept: e.target.value } })} /></Field></div>
      <div className="mt-3"><Field label="Ringkasan Materi Esensial"><TextArea rows={5} value={rpp.essentialMaterial.summary} onChange={(e) => onChange({ ...rpp, essentialMaterial: { ...rpp.essentialMaterial, summary: e.target.value } })} /></Field></div>
      <div className="mt-3 grid gap-3 sm:grid-cols-2"><LineListEditor label="Refleksi Peserta Didik" values={rpp.studentReflectionQuestions} onChange={(studentReflectionQuestions) => onChange({ ...rpp, studentReflectionQuestions })} /><LineListEditor label="Refleksi Guru" values={rpp.teacherReflectionQuestions} onChange={(teacherReflectionQuestions) => onChange({ ...rpp, teacherReflectionQuestions })} /></div>
      <div className="mt-3 grid gap-3 sm:grid-cols-2"><LineListEditor label="Remedial" values={rpp.remedialActivities} onChange={(remedialActivities) => onChange({ ...rpp, remedialActivities })} /><LineListEditor label="Pengayaan" values={rpp.enrichmentActivities} onChange={(enrichmentActivities) => onChange({ ...rpp, enrichmentActivities })} /></div>
    </EditorSection>

    <EditorSection title="Rubrik Penilaian" description="Sunting deskriptor rubrik sebelum dokumen diekspor.">
      <div className="space-y-5"><RubricEditor label="Rubrik Kinerja" items={rpp.performanceRubric} onChange={(performanceRubric) => onChange({ ...rpp, performanceRubric })} /><RubricEditor label="Rubrik DPL" items={rpp.graduateProfileRubric} onChange={(graduateProfileRubric) => onChange({ ...rpp, graduateProfileRubric })} /><RubricEditor label="Rubrik Produk" items={rpp.productRubric || []} onChange={(productRubric) => onChange({ ...rpp, productRubric })} /></div>
    </EditorSection>

    {rpp.studentWorksheet ? <EditorSection title="LKPD" description="Review stimulus, masalah, langkah, tugas, dan prompt produk.">
      <Field label="Judul"><TextInput value={rpp.studentWorksheet.title} onChange={(e) => onChange({ ...rpp, studentWorksheet: { ...rpp.studentWorksheet!, title: e.target.value } })} /></Field>
      <div className="mt-3"><LineListEditor label="Tujuan" values={rpp.studentWorksheet.objectives} onChange={(objectives) => onChange({ ...rpp, studentWorksheet: { ...rpp.studentWorksheet!, objectives } })} /></div>
      <div className="mt-3 grid gap-3 sm:grid-cols-2"><Field label="Situasi Awal"><TextArea rows={4} value={rpp.studentWorksheet.stimulus} onChange={(e) => onChange({ ...rpp, studentWorksheet: { ...rpp.studentWorksheet!, stimulus: e.target.value } })} /></Field><Field label="Rumusan Masalah"><TextArea rows={4} value={rpp.studentWorksheet.problemFormulation} onChange={(e) => onChange({ ...rpp, studentWorksheet: { ...rpp.studentWorksheet!, problemFormulation: e.target.value } })} /></Field></div>
      <div className="mt-3 grid gap-3 sm:grid-cols-2"><LineListEditor label="Langkah Penyelidikan" values={rpp.studentWorksheet.studySteps} onChange={(studySteps) => onChange({ ...rpp, studentWorksheet: { ...rpp.studentWorksheet!, studySteps } })} /><LineListEditor label="Tugas Penyelidikan" values={rpp.studentWorksheet.investigationTasks} onChange={(investigationTasks) => onChange({ ...rpp, studentWorksheet: { ...rpp.studentWorksheet!, investigationTasks } })} /></div>
      <div className="mt-3 grid gap-3 sm:grid-cols-2"><Field label="Pertanyaan Kesimpulan"><TextArea rows={3} value={rpp.studentWorksheet.conclusionPrompt} onChange={(e) => onChange({ ...rpp, studentWorksheet: { ...rpp.studentWorksheet!, conclusionPrompt: e.target.value } })} /></Field><Field label="Tantangan / Produk"><TextArea rows={3} value={rpp.studentWorksheet.challengeOrProductPrompt} onChange={(e) => onChange({ ...rpp, studentWorksheet: { ...rpp.studentWorksheet!, challengeOrProductPrompt: e.target.value } })} /></Field></div>
    </EditorSection> : null}
  </>;
}
